# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Build and publish

on:
  push:
    branches:
      - master

jobs:
  build_and_publish:
    name: "Build and Publish"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - run: npm ci
      - run: npm test
      - run: npm run build
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'
      - run: cp .npmrc dist/.npmrc
      - run: npm publish --provenance
        working-directory: dist
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
